targets:
  $default:
    sources:
      - swaggers/**
      - lib/**
      - $package$
    builders:
      chopper_generator:
        options:
          header: "//Generated code"
      swagger_dart_code_generator:
        options:
          input_folder: "swaggers/"
          output_folder: "lib/api_prof_d/"
          input_urls:
            - "http://localhost:3000/api-json"
          with_base_url: true
          with_converter: true
          use_default_null_for_lists: false
          build_only_models: false
          separate_models: true
          enums_case_sensitive: false
          ignore_headers: false
          use_required_attribute_for_headers: false
          include_if_null: true
