name: prof_d
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  cupertino_icons: ^1.0.5
  # flutter
  flutter:
    sdk: flutter

  # Firebase
  cloud_firestore: ^3.4.2
  firebase_auth: ^3.6.1
  firebase_core: ^1.20.0
  firebase_storage: ^10.3.4
  cloud_functions: ^3.3.3
  firebase_messaging: ^12.0.1

  # stateManagement
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  flutter_riverpod: ^1.0.4
  flutter_hooks: ^0.18.5+1
  hooks_riverpod: ^1.0.4

  # LocalStorage
  shared_preferences: ^2.0.15
  sqflite: ^2.0.3
  image_picker: ^0.8.5+3

  # Swagger
  chopper: ^4.0.6

  #Ecosystem
  get: ^4.6.5

  # Webview
  webview_flutter: ^3.0.4

  #Screen Introduction
  introduction_screen: ^3.0.2

  # Responsive
  sizer: ^2.0.15
  flutter_screenutil: ^5.5.3+2


  #Connectivity
  connectivity_plus: ^2.3.6
  internet_connection_checker: ^0.0.1+4

  # Location
  location: ^4.4.0

  # Apis
  dio: ^4.0.6
  # Grid
  flutter_staggered_grid_view: ^0.6.2

  # Widget
  flutter_login: ^4.0.0

  # Images
  lottie: ^1.4.0
  cached_network_image: ^3.2.1
  flutter_svg: ^1.1.1+1


  # Utils
  flutter_fadein: ^2.0.0
  flutter_localizations: # Add this line
    sdk: flutter
  flutter_local_notifications: ^9.7.0
  animate_navigator_transition_do: ^1.1.0
  datetime_picker_formfield: ^2.0.0
  flutter_feather_icons: ^2.0.0+1
  google_fonts: ^3.0.1
  model_generator: ^5.8.1
  formz: ^0.4.1
  google_place: ^0.4.7
  json_annotation: ^4.6.0
  dio_logging_interceptor: ^1.0.1
  timezone: ^0.8.0
  syncfusion_flutter_calendar: ^20.2.40 # TODO à ranger
  syncfusion_localizations: ^20.2.40
  syncfusion_flutter_pdfviewer: ^20.2.40-beta
  flutter_pdfview: ^1.2.2
  share_plus: ^4.0.10


  # Environement
  flutter_dotenv: ^5.0.2

  # UI
  flutx:
    path: packages/flutx


  # Packages
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/image/logo.png"

dev_dependencies:
  build_runner:
  json_serializable: ^6.3.1
  dart_code_metrics: ^4.17.0
  flutter_launcher_icons: ^0.9.3
  flutter_lints: ^2.0.1
  chopper_generator: ^4.0.6
  swagger_dart_code_generator: any
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - .env.development
    - .env.production
    - assets/animation/loading.json
    - assets/images/core/dialog_widget_icons/
    - assets/images/core/dialog_widget_icons/warning.png
    - assets/animation/create_animation.json
    - assets/home_page_image.svg
    - assets/image/logo.jpg
    - assets/images/
    - assets/images/core/
    - assets/images/apps/medicare/
    - assets/images/profile/
    - assets/images/welcome/
    - assets/images/login/
    - assets/json/
    - assets/images/introduction_screen/
    - assets/images/introduction_screen/profile.jpg
    - assets/images/introduction_screen/4238140.jpg
    - assets/images/home/empty_state/bg-4.svg
    - assets/images/home/empty_state/bg-4.png
    - assets/images/home/empty_state/
    - assets/images/profile/flying-a-kite.svg
    - assets/images/appointment/clock.svg
    - assets/images/appointment/empty_state/
    - assets/images/admin/
    - packages/timezone/data/2020a.tzf

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
